from fpdf import FPDF
import os

class FragmentPDF(FPDF):
    def header(self):
        # Logo or Title Bar
        self.set_fill_color(26, 26, 26) # Dark background for header
        self.rect(0, 0, 210, 30, 'F')
        self.set_text_color(255, 255, 255)
        self.set_font('Helvetica', 'B', 20)
        self.cell(0, 10, 'FRAGMENT FIRST', 0, 1, 'C')
        self.set_font('Helvetica', 'I', 10)
        self.cell(0, 5, 'Trauma-Informed Memory Account', 0, 1, 'C')
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Generated by Fragment First AI - Page {self.page_no()}', 0, 0, 'C')

    def chapter_title(self, title, color=(255, 77, 109)):
        self.set_text_color(*color)
        self.set_font('Helvetica', 'B', 16)
        self.cell(0, 10, title, 0, 1, 'L')
        self.line(self.get_x(), self.get_y(), self.get_x() + 190, self.get_y())
        self.ln(5)

    def chapter_body(self, body):
        self.set_text_color(40, 40, 40)
        self.set_font('Helvetica', '', 11)
        self.multi_cell(0, 8, body)
        self.ln()

def generate_pdf(content: str, filename: str):
    pdf = FragmentPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    
    # Split content into Narrative and Explainer based on AI output tags
    sections = content.split("Trauma Science Explainer")
    
    narrative = sections[0].replace("Structured Narrative Account", "").strip()
    explainer = sections[1].strip() if len(sections) > 1 else ""

    pdf.chapter_title("Structured Narrative Account", color=(157, 78, 221)) # Purple accent
    pdf.chapter_body(narrative)
    
    if explainer:
        pdf.add_page()
        pdf.chapter_title("Trauma Science Explainer", color=(255, 183, 3)) # Orange accent
        pdf.chapter_body(explainer)
        
        # Add a note about trauma science
        pdf.ln(10)
        pdf.set_font('Helvetica', 'I', 9)
        pdf.set_text_color(100, 100, 100)
        pdf.multi_cell(0, 5, "Note: This document contextualizes fragmented memory through the lens of trauma biology (neuroplasticity and amygdala response) to support legal professionals in understanding testimony consistency.")

    pdf.output(filename)
    return filename
